name: rekognition
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  rekognition_data_source:
    path: ../rekognition_data_source
  aws_rekognition_api: ^2.0.0
  equatable: ^2.0.5
  json_annotation: ^4.7.0
  meta: ^1.8.0
  envied: ^0.3.0

dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  json_serializable: ^6.5.4
  lints: ^2.0.0
  test: ^1.16.0
