name: CalendarLibrary
language: objc
output: "calendar_bindings.dart"
exclude-all-by-default: true
objc-interfaces:
  include:
    - "NSCalendarDate"
headers:
  entry-points:
    - "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSCalendarDate.h"
preamble: |
  // ignore_for_file: camel_case_types, non_constant_identifier_names, unused_element, unused_field, return_of_invalid_type, void_checks, annotate_overrides, no_leading_underscores_for_local_identifiers, library_private_types_in_public_api,constant_identifier_names,depend_on_referenced_packages